### ISSUE TITLE
Is this a school project or what?

### ISSUE THREAD

**Issue by legoboy0215** [Gamecrafter/Pi-Project#1]
IDK.

**Comment by ifvictr** [comment]
Yeah this was a school project. :stuck_out_tongue: I've been doing a lot of web-based things for all my school projects for awhile now.

**Comment by legoboy0215** [comment]
Why? School requirement?

**Comment by ifvictr** [comment]
No, just for fun. Also something to brag about. :stuck_out_tongue:

**Comment by legoboy0215** [comment]
XD Like: 'I know how to code! Kneel down!'

**Comment by ifvictr** [comment]
Lol something like that but not like that
