### ISSUE TITLE
Tau

### ISSUE THREAD

**Issue by PEMapModder** [Gamecrafter/Pi-Project#2]
# Hi, my name is Tau.

> You've probably heard about me from your math teachers or whatsoever.

You are ignoring me in your website.

I am very famous. I even appeared on the [xkcd webcomic](https://xkcd.com/1292/).

And you neglected me.

This is not unforgivable though. There is a way that we can reach compromise. Change this project to the Pau-project. Let's take our arithmetic mean.

![](https://imgs.xkcd.com/comics/pi_vs_tau.png)

And you must not ignore this issue. Or terrible things will happen on you for disrespecting the devil.

> Conveniently approximated as e+2, Pau is commonly known as the Devil&#39;s Ratio (because in the octal expansion, &#39;666&#39; appears four times in the first 200 digits while no other run of 3+ digits appears more than once.)

**Comment by ifvictr** [comment]
:+1: I don't even know what a "tau" is... Let's just stick with pi...
